# ************************************************************
# Sequel Pro SQL dump
# Version 4096
#
# http://www.sequelpro.com/
# http://code.google.com/p/sequel-pro/
#
# Host: 127.0.0.1 (MySQL 5.5.34-0ubuntu0.12.04.1)
# Database: blog
# Generation Time: 2015-02-24 13:12:47 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table posts
# ------------------------------------------------------------

DROP TABLE IF EXISTS `posts`;

CREATE TABLE `posts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL DEFAULT '',
  `body` text NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `posts` WRITE;
/*!40000 ALTER TABLE `posts` DISABLE KEYS */;

INSERT INTO `posts` (`id`, `title`, `body`, `created`, `modified`)
VALUES
    (1,'Laïcité – Le gouvernement ordonne la destruction de la ville de Lourdes','Le gouvernement vient d’annoncer une série de nouvelles mesures visant à renforcer la laïcité en France. Au programme, un plan visant à renforcer l’interdiction des signes religieux distinctifs dans l’espace public. Plusieurs symboles religieux se voient menacés de destruction, dont notamment la ville de Lourdes. Reportage.\r\n\r\nLes habitants de la ville de Lourdes, située dans les Hautes-Pyrénées, se sont réveillés ce matin avec l’étrange impression de vivre avec une épée de Damoclès au-dessus de la tête. Car si le gouvernement a bien annoncé hier qu’il comptait démonter pierre par pierre toute la ville, il n’a pas fournit le moindre calendrier précis aux Lourdais. « Je ne comprends pas, je fais des prières pour le gouvernement depuis ce matin pour les faire changer d’avis » explique une habitante apeurée.\r\n\r\nCe qui est reproché à la ville de Lourdes, c’est justement son côté religieux, trop présent et trop ostentatoire au goût du gouvernement. « Pour ce qu’elle représente, cette ville devient une menace pour la laïcité, garant de l’unité de notre pays qui ne peut tolérer la présence d’un symbole religieux aussi puissant en son sein » a déclaré le premier ministre hier en conférence de presse.\r\n\r\nFortement commentée dans les médias et sur les réseaux sociaux, la destruction programmée de la ville de Lourdes cache d’autres mesures moins médiatiques, mais tout aussi radicales. Entre autres, un mur de plus de 1500 mètres de haut devrait être érigé devant le Mont Saint-Michel pour le masquer. C’en est bientôt fini aussi du traditionnel chemin de Saint-Jacques de Compostelle sur le territoire français, puisque les pèlerins seront prochainement invités à emprunter une voie privée.','2015-02-24 11:38:05','2015-02-24 11:38:05'),
    (2,'Comprendre la digestion de Rihanna','Rihanna postait l’autre jour sur Instagram une image de son brunch qui nous a toutes fait rêver. Mais que s’est-il passé après ? Madame Gorafi vous dit tout.\r\n\r\nQuand Rihanna mange, elle mâche des aliments. La nourriture est, grâce au procédé dit de la mastication, mélangée à la salive de Rihanna. Puis la chanteuse avale le tout. Mais le corps de Rihanna a, à ce moment-là encore beaucoup d’efforts à faire avant que tout soit digéré. En effet, les aliments transformés en molécules passent alors par l’oesophage de Rihanna, que vous pouvez deviner sous son décolleté dans les dernières photos qu’elle a postées sur son blog.\r\n\r\nPuis, la nourriture arrive dans l’estomac de Rihanna, qui envoie des sucs gastriques afin que son repas soit totalement digéré. C’est souvent un moment où Rihanna se repose, car c’est une étape très fatigante. Ensuite, la mixture est envoyée vers l’intestin grêle de Rihanna. Le pancréas de Rihanna secrète alors des enzymes qui permettent de récupérer les protéines, et autres vitamines, afin que Rihanna ait des forces pour faire ses chansons.\r\n\r\nEnfin, tout ce qui n’a pas été transformé en énergie est dès lors envoyé vers son colon. Rihanna est alors obligée de se rendre aux toilettes et ce une à deux fois par jour.  La chanteuse va s’asseoir sur ses toilettes pendant plusieurs minutes et peut parfois lire un magazine en attendant.\r\n\r\nDurant ce laps de temps, le colon de Rihanna évacue, non sans douleurs parfois, la totalité des déchets liés à son repas. Durant le reste de sa journée et de sa vie, la chanteuse devrait reproduire plusieurs centaines de milliers de fois ce cycle.\r\n\r\nAlors, heureuse d’en savoir plus sur Rihanna ? Vous n’écouterez plus jamais Diamonds de la même façon !','2015-02-24 11:38:30','2015-02-24 11:38:30'),
    (3,'Quels cadeaux offrir à son enfant pour lui faire comprendre qu’il n’était pas désiré ?','Vous avez dépassé le délai pour l’avortement et vous voulez raconter à votre enfant l’histoire tragique de ses origines. Pour lui faire comprendre l’absence de raison de son existence, offrez-lui le cadeau parfait.\r\n\r\nUn DVD de Jamy et Fred sur la contraception. Avec ce présent, votre enfant comprendra ce que veut dire votre phrase favorite : « si seulement j’avais pris la pilule ». Ajoutez une carte à ce petit cadeau où vous aurez préalablement écrit : « ne fais pas la même bêtise que moi », et votre enfant devrait avoir bien compris qu’il ou elle n’aurait pas dû naître.\r\n\r\nLe guide du bon Djihadiste. Vous n’avez jamais eu envie d’avoir cet enfant, alors plus vite il ou elle sera partie, mieux ce sera. Avec le guide du bon Djihadiste, votre enfant devrait prendre un aller simple pour la Syrie très rapidement, et ce sera comme s’il n’avait jamais existé. En cas de décès les frais d’enterrements dispendieux seront à la charge de Daesh.\r\n\r\nLe lien URL de cet article. Très simple et rapide, il vous suffira de réaliser un copié collé de l’url de cet article dans votre barre des tâches et de l’envoyer ensuite à votre enfant au travers de son réseau social préféré. Il ou elle comprendra alors immédiatement le message on ne peut plus clair.\r\n\r\nUn poupon en lui disant « j’avais plus envie de m’occuper de cette chose que de toi ». Attention, il ou elle pourrait comprendre qu’il ou  elle  n’a pas été un bébé agréable. Par conséquent, rappelez-lui surtout qu’il ou elle n’a pas été un fœtus agréable non plus.\r\n\r\nUne photo de famille où il ou elle est remplacé par le chien. Un chien, c’est sympa, ça ne demande pas trop d’attention, et ça ne détruit pas votre vagin avant d’arriver à la maison. Tant de qualités dont votre enfant n’a pas fait preuve : il est temps qu’il ou elle en prenne conscience. Avec cette photographie, que vous pouvez encadrer selon vos goûts, il ou elle devrait comprendre que vous auriez préféré caresser un animal plutôt que de changer ses couches.','2015-02-24 11:39:02','2015-02-24 11:39:02'),
    (4,'Valls utilise le 49.3 pour faire passer en force les frites à la cantine de l’Assemblée','Hier, en fin d’après-midi, le gouvernement a dégainé l’article 49.3 de la Constitution afin de faire passer le texte sur les frites à la cantine de l’Assemblée sans le vote de cette dernière. Retour sur ce passage en force de l’exécutif.\r\n\r\n« J’ai décidé d’engager ma responsabilité. Les réformes alimentaires vont se poursuivre » a confié le premier ministre hier soir sur TF1. Rejetant les accusations de déni de démocratie, Manuel Valls a poursuivi : « C’est le symbole de ma détermination en matière de menu du midi. »\r\n\r\n«La responsabilité du gouvernent, c’était d’avancer. Les Frites, c’est l’avenir, et les Français responsables le savent. » a soutenu de son côté Emmanuel Macron. Le ministre de l’économie a justifié l’usage de l’article 49.3 pour faire passer sa loi : « Le menu de la cantine, on ne le joue pas aux dés. Il faut comprendre la réalité de la situation dans ce réfectoire. ». « Être de gauche, c’est donner la possibilité aux députés de manger des frites à la cantine. » a enfin ajouté Emmanuel Macron.\r\n\r\nPour de nombreuses personnes de l’opposition, c’est un « véritable passage en force culinaire  » Mélenchon, scandalisé, s’est notamment exprimé « Les Français n’ont pas voté pour ça en 2012. Ils ont un véritable amour pour leur gastronomie, un patriotisme culinaire, qui les retient de soutenir les frites congelées. Et pourquoi pas des potatoes tant qu’on y est ? »','2015-02-24 11:39:19','2015-02-24 11:39:19'),
    (5,'Fort Boyard : Un candidat oublié dans la cellule d’une épreuve retrouvé 7 ans plus tard','La Rochelle – Stupeur et incompréhension pour France Télévision après la découverte de ce week-end. Un homme, ancien candidat de l’émission Fort Boyard, dit avoir été oublié lors d’une épreuve du célèbre jeu dans une des cellules, il y a plus de sept ans. Reportage.\r\n\r\nLe visage émacié, amaigri, Aymeric Ledeb revient de loin. L’homme, actuellement hospitalisé au CHU de la Rochelle, n’a pas encore raconté l’intégralité de son histoire aux enquêteurs mais on commence peu à peu à comprendre ce qui s’est passé. « C’était lors d’une épreuve de l’émission enregistrée sur le Fort. Il devait trouver un clé dans une série de jarres remplies de souris, insectes et autres matières visqueuses. Il n’a hélas pas pu terminer à temps et il est resté prisonnier comme le veut la règle », a expliqué un gendarme. Pour une raison jusqu’ici inexpliquée, le reste de ses coéquipiers va alors l’oublier dans sa cellule après la fin de l’émission. « Chacun a pensé qu’il était rentré par ses propres moyens, ou que vexé d’avoir échoué, il ne voulait pas reparler aux autres membres de l’équipe » raconte Ingrid, sa coéquipière de l’époque.\r\n\r\nL’enregistrement terminé, toutes les équipes regagnent ensuite le continent, laissant Aymeric à son triste sort. « L’épreuve a été supprimée lors de l’émission suivante et nous avons cessé d’utiliser cette partie du Fort pour les tournages. Personne n’est allé voir dans cette cellule, qui a été oubliée ensuite. Il y a des centaines de cellules de ce type dans tout le Fort » explique pour sa part Colin Jamiel, producteur de l’émission. Les murs très épais du site vont contenir les appels à l’aide de Aymeric. Le jeune homme va survivre miraculeusement en se nourrissant d’araignées, de souris, de rats  et de racines.\r\n\r\nLe calvaire d’Aymeric va durer ainsi sept longues années. Jusqu’à ce week-end, quand une équipe chargée de la rénovation de certaines parties du Fort rouvre sa cellule. Ils y découvrent un homme blafard, les cheveux longs, presque aveugle. Pris en charge immédiatement par les secours, l’homme est rapidement hospitalisé. « Pendant qu’on s’occupait de lui, on a remarqué qu’il tenait quelque chose dans sa main, une petite clé » raconte un des pompiers. Ce qui prouverait donc que Aymeric avait donc presque réussi l’épreuve à l’époque.\r\n\r\nPour l’instant l’ancien candidat n’a pas fait part d’une quelconque volonté de poursuivre en justice ses anciens camarades ainsi que la production de l’émission. S’il remportait un tel procès, les propriétaires du Fort pourraient bien débourser une somme astronomique de leur fameux boyards pour réparer le préjudice moral, mettant potentiellement en danger l’avenir de l’émission.','2015-02-24 11:39:44','2015-02-24 11:39:44'),
    (6,'Le dernier fan du groupe G-Squad reconnaît se sentir un peu seul','ll n’y a encore pas si longtemps ils étaient une dizaine, mais aujourd’hui il n’y a plus que lui. Roman Crabère, 28 ans, est le dernier fan du groupe G-Squad qui avait marqué les années 1990 avec des titres tels que « Raide dingue de toi » et « Touché en plein coeur ». Le Gorafi est allé à sa rencontre.\r\n\r\n« 2013 a été une année difficile »\r\n\r\nRoman explique qu’en 2012 le fan club des G-Squad comptait une bonne quinzaine de membres sur toute la France, une époque faste qu’il évoque avec nostalgie. « 2013 a été une année difficile. On était encore deux début 2014 mais Hugo aussi a fini par partir. C’est dur, évidemment, mais ce qu’ils font est très puissant, ça aide à tenir. Et puis j’ai trop investi en posters et en CD 2 titres, je peux pas lâcher maintenant. »\r\n\r\nS’il continue à suivre leur actualité chaque jour, c’est aussi parce que Roman attend l’annonce imminente de leur prochain album qu’ils élaboreraient dans le secret de leur studio.\r\n\r\nLorsque l’on évoque l’échec de Chris Keller au casting de The Voice, Roman s’emporte. « Si Chris en est arrivé là c’est à cause de ces gros bâtards du fan club d’Alliage, les frères Flumin. Depuis 1998 ils font tout pour empêcher les G-Squad de sortir leur album ! »\r\n\r\nRelancer le groupe en fusionnant avec les 2B3 et Zaz\r\n\r\nDans l’espoir de voir venir des jours meilleurs, Roman a un plan qu’il compte soumettre à ses idôles. « Il faudrait fusionner le groupe avec Franck et Adel des 2B3 et avec Zaz. Déjà musicalement ça pourrait envoyer du lourd et surtout, en réunissant nos fans clubs respectifs on atteindrait facilement les vingt membres. Le rêve ! »','2015-02-24 11:40:05','2015-02-24 11:40:05'),
    (7,'Pascal Obispo : « La situation en France est grave, il va falloir que je sorte un nouvel album »','Nous l’espérions sans vraiment y croire, Pascal Obispo est sorti du silence ce matin.\r\n\r\nSobre et discret comme à son habitude, le chanteur a posté un simple message sur twitter pour annoncer la nouvelle : « La situation en France est grave, il va falloir que je sorte un nouvel album. #JeSuisPascal »\r\n\r\n« Ils m’ont dit, Pascal, la France a besoin de toi »\r\n\r\nContacté par la rédaction du Gorafi, l’intéressé a accepté de nous raconter la génèse de cet album, lueur naissante au coeur des ténèbres. « Après les évènements j’ai eu besoin de me foutre au piano pour sortir toute ma rage. Par hasard il y avait à ce moment-là des amis proches, mon producteur, mon banquier. Ils m’ont dit, Pascal, la France a besoin de toi. Alors j’ai dit OK. Cet album sera ma révolte : un homme en colère, 12 titres, 9,99 euros sur Itunes. »\r\n\r\nMalgré l’engouement, les fans sont nombreux à s’inquiéter des risques que prend leur idole. Touché par ce mouvement de soutien, l’artiste a tenu à faire une petite mise au point. « Bien sûr que j’ai peur, mais être artiste c’est pas toujours un plaisir. Ma musique c’est mon arme, ma mitraillette contre leurs mitraillettes. Sur certains tracks je serai en featuring avec des artistes comme Zaz ou Shy’m. On va leur faire mal. »\r\n\r\nNégocier pour éviter la surenchère\r\n\r\nDepuis, plusieurs hauts dignitaires de Daesh ont pris la parole pour proposer d’ouvrir des négociations afin de ne pas tomber dans la surenchère. « Sachez que nous avons largement de quoi répondre à M. Obispo. Ne rentrez pas dans ce jeu avec nous, sinon nous lancerons la production d’un nouvel album de Tarkan, et alors nous ne répondrons plus de rien. »','2015-02-24 11:40:23','2015-02-24 11:40:23'),
    (8,'Le nouveau livre de Marc Levy sera publié au dos des paquets de Chocapic','C’est un véritable coup éditorial que vient de réaliser Marc Levy en annonçant la publication de son prochain roman, « Elle et lui » , au dos des paquets de Chocapic. Un tirage à plus de 40 000 exemplaires par jour qui place directement le romancier en tête des ventes.\r\n\r\n« Être au plus proche de nos lecteurs »\r\n\r\nÀ l’origine de cette idée révolutionnaire, il y a un homme, Jean Letanneur, directeur marketing chez Robert Laffont. « Avec Marc nous avions déjà capté les mères de famille, les jeunes filles célibataires et les seniors sur le retour mais nous n’arrivions pas à toucher les 6-13 ans. Les ingrédients des paquets de céréales font partie des publications les plus populaires chez les jeunes, il suffisait d’y penser ! » explique-t-il tout sourire.\r\n\r\nL’enjeu était évidemment de faire tenir tout un roman à l’arrière d’un paquet de Chocapic, un défi que Marc Levy a vécu comme l’aboutissement d’un processus créatif. « Dans mes anciens romans je m’efforçais déjà d’aller à l’essentiel en évitant les idées trop complexes. Pas besoin de se prendre la tête pour pleurer. Pour celui-ci, il a simplement fallu supprimer certains mots qui ne servent à rien. Et puis le fait de pouvoir intégrer de petits jeux apporte beaucoup à l’intrigue » explique l’intéressé.\r\n\r\nLa réponse de Guillaume Musso\r\n\r\nLa maison d’édition de Guillaume Musso n’a pas tardé à répliquer. Pour « catcher » le public encore plus en amont, le prochain roman du prolifique auteur intitulé Et mince je t’aime ne sera pas publié du tout mais sera en revanche lu par des puéricultrices en crèche lors de la sieste des enfants. « C’est révolutionnaire, ils ne se souviendront de rien mais nous sommes convaincus que petit à petit va s’installer dans leur inconscient une saine dépendance » explique-t-on chez Xo Editions.','2015-02-24 11:40:44','2015-02-24 11:40:44');

/*!40000 ALTER TABLE `posts` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
